### ISSUE TITLE
Key class conflict on Flutter project

### ISSUE THREAD

**Issue by dvshin** [primes-network/eosdart#12]
Key class  on models/account.dart currently conflict with flutter foundation/key.dart
If this project can trigger push transaction... Your are the best!

**Comment by fzxu** [comment]
it should be fixed in 0.3.1. let me know if you still have issue. Will support push transaction for sure, stay tuned.

**Comment by mgravitt** [comment]
It would be fantastic to support push transaction. Let me know if I can help!
