### ISSUE TITLE
Add push action method

### ISSUE THREAD

**Issue by 0xbakunawa** [primes-network/eosdart#16]
Great lib. It will be great if you can add push action method.

Thx

**Comment by fzxu** [comment]
Yes, it is working in progress. I only work on this project part time, so it may take a while...

**Comment by yanxi123-com** [comment]
+1, and I want to getTable() as well

**Comment by VNadygin** [comment]
@fzxu Hey. Any progress on `transact` method? I am also waiting for it

**Comment by fzxu** [comment]
The initial version is supported. Please check the README and examples folder.
