### ISSUE TITLE
Signature are not canonical

### ISSUE THREAD

**Issue by VNadygin** [primes-network/eosdart#21]
I know I should be fixed but with 50% chance the error appears

**Comment by fzxu** [comment]
Could you provide the testing data that is non canonical?

**Comment by bee-warrior** [comment]
@fzxu Hey. Sorry for not responding for a long time.

Can you specify which data do you need for fixing?

```
{signatures: [SIG_K1_KCAfUUGmTc8XDFfEpbfqcY8e2dZtRK1EYJK1fXkRCFQyxTmsapLvPCYCxKRNTXATdf8WTaWuyuvgUriu3hTGFrXnubACeB], compression: 0, packed_context_free_data: , packed_trx: 5B16F05C0DEE8E2C132B000000000100C0549066D0CDC4000000572D3CCDCD01000090EA9141AF8200000000A8ED323221000090EA9141AF8200C0A5EE5EC3953A010000000000000004534E41580000000000}
```

**Comment by VNadygin** [comment]
@fzxu Hey. Could you specify which data do you need for fixing and debugging?

This payload respond with signature are not canonical for example
```{signatures: [SIG_K1_Kq3MhVijnX2ZaE3JQ3FsKMFSbgV5U9cEnUp4xs8i9685dD446cezWBytTGCAwtaLUUagRQZbj2UFd74neWcS7Acv1V8EQg], compression: 0, packed_context_free_data: , packed_trx: 3B17F05CCEEFAB5B80A7000000000100C0549066D0CDC4000000572D3CCDCD01000090EA9141AF8200000000A8ED323221000090EA9141AF8200C0A5EE5EC3953A010000000000000004534E41580000000000}```

**Comment by fzxu** [comment]
could you try the latest version see if the issue got resolved? @VNadygin

**Comment by fzxu** [comment]
should be fixed.
